config/routes.rb
NewProject::Application.routes.draw do
  resources :users
  resources :authentications, only: [:new, :create, :destroy]
  resources :skills
  resources :categories
  resources :mentors
  resources :learners

  root  'static_pages#home'
  match '/signin',            to: 'authentications#new',      via: 'get'
  match '/skills/:id/edit',   to: 'skills#update',            via: 'post'
  match '/mentors/:id/edit',  to: 'mentors#update',           via: 'post'
  match '/learners/:id/edit', to: 'learners#update',          via: 'post'
  match '/logout',            to: 'static_pages#logout',      via: 'get'
  match '/signout',           to: 'authentications#destroy',  via: 'delete'
  match '/help',              to: 'static_pages#help',        via: 'get'
  match '/about',             to: 'static_pages#about',       via: 'get'
  match '/contact',           to: 'static_pages#contact',     via: 'get'
  

  

end

app/models/category.rb
class Category
	include Mongoid::Document

field :category_name, type: String

has_many :skills

end

app/models/learner.rb
class Learner #learning experience
	include Mongoid::Document

#fields to include what to learn
field :notes, type: String

# has_many :agreements
belongs_to :user
# belongs_to :skill
has_and_belongs_to_many :skills



end

app/models/mentor.rb
class Mentor #mentoring experience
	include Mongoid::Document

#fields to include what to mentor
field :notes, type: String
# field :courses_description, type: String



# has_many :agreements
belongs_to :user
# belongs_to :skill
has_and_belongs_to_many :skills

end

app/models/skill.rb
class Skill
	include Mongoid::Document

	attr_accessor :m_or_l, :notes, :bio, :objectives, :goals

	field :skill_name, type: String
	field :skill_description, type: String

	
	
	has_and_belongs_to_many :learners, dependent: :destroy
	has_and_belongs_to_many :mentors, dependent: :destroy
	# has_many :learners
	# has_many :mentors
	belongs_to :category


end

app/models/user.rb
require 'bcrypt'

class User
	include Mongoid::Document

	attr_accessor :password, :password_confirmation

	field :name, type: String
	
	field :email, type: String
	field :salt, type: String
	field :hashed_password, type: String

	field :location, type: String
	field :language, type: String
	field :interest, type: String
	

	before_save :hash_password

	validates :email, presence: true
	validates :email, uniqueness: { case_sensitive: false }
	validates :password, confirmation: true 

	def authenticate(password)
		self.hashed_password ==
		BCrypt::Engine.hash_secret(password, self.salt)
	end


	private
	def hash_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.hashed_password = 
			BCrypt::Engine.hash_secret(password, self.salt)
			password = password_confirmation = nil
		end
	end

	has_many :mentors
	has_many :learners
	has_many :skills
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
	if session[:user_id]
		@current_user ||= User.find_by(id: session[:user_id])
	end
  end

	def authenticate_user
		redirect_to root_url unless current_user
	end

	
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
	#only call into
	before_action :authenticate_user, only: [:destroy]


	def new
		# are they already logged in?
		if current_user #they are!  can't create them again
			redirect_to user
		else
			@user = User.new

			render :new  # i dont know if this function actually works!
		end
	end	


	def create
			user = User.find_by(email: params[:user][:email])
		# if user
		if user != nil
			#authenticate user and then redirect them to user profile page
			if user.authenticate(params[:user][:password])
				session[:user_id] = user.id
				redirect_to user
			end
		else
			flash.now[:error] = "Unable to sign you in."
			# render :new
			redirect_to new_user_path
		end
		# end
	end

	def destroy
		session[:user_id] = nil
		redirect_to logout_path
		
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def show
		@category = Category.find(params[:id])
		
		@skill = @category.skills.new
	end

	# def create
	# 	@category = Category.create(params[:category].permit(:category_name))
	# 	redirect_to :action => "show", :id =>@category._id
	# end

	def update
		Skill.all.each do |s|
			params.each do |key, value|
				if key[0]=="m"
					if s.id.to_s ==key[1..key.length-1]
						m = s.mentors.new
						m.user = current_user
						m.save
						redirect_to mentor_path
					end
				elsif key[0]=="l"
					if s.id.to_s ==key[1..key.length-1]
						l = s.learners.new
						l.user = current_user
						l.save
						redirect_to learner_path
					end
				end
			end
		end
		# redirect_to :controller => 'users', :action => 'show', :id => @user._id
	end

	def destroy
		Category.find(params[:id]).destroy
		redirect_to categories_url
	end
end

app/controllers/learners_controller.rb
class LearnersController < ApplicationController

	def index
		@learners = Learner.all
	end

	def show
		@learner = Learner.find(params[:id])
	end

	def edit
		@learner = Learner.find(params[:id])
	end

	def update
		@learner = Learner.find(params[:id])

		if @learner.update_attributes(params[:learner].permit(:notes))
			redirect_to action: 'show', id: @learner
		else
			render 'edit'
		end
	end

end

	

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController

	def index
		@mentors = Mentor.all
	end

	def show
		@mentor = Mentor.find(params[:id])
	end

	def edit
		@mentor = Mentor.find(params[:id])
	end

	def update
		@mentor = Mentor.find(params[:id])

		if @mentor.update_attributes(params[:mentor].permit(:notes))
			redirect_to action: 'show', id: @mentor
		else
			render 'edit'
		end
	end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	def index
		@skills = Skill.all

	end

	def new
		@skill = Skill.new
	end

	def show
		@skill = Skill.find(params[:id])
		# this doesnt work.  how do i show mentor/learner info?
		# @mentor = Skill.mentor.find(params[:skill])
		# @learner = Skill.learner.find(params[:skill])
	end

	def create
		@skill = Skill.create(params[:skill].permit(:skill_name, :category_id, :skill_description))
		
			if params[:skill][:m_or_l] == 'mentor'
				m = @skill.mentors.new(:notes => params[:skill][:notes])
				m.user = current_user
				m.save
			else
				l = @skill.learners.new(:notes => params[:skill][:notes])
				l.user = current_user
				l.save
			end

		redirect_to :controller => 'categories', :action => 'show', :id => params[:skill][:category_id]
	end

	def edit
		@skill = Skill.find(params[:id])
	end

	def update
		@skill = Skill.find(params[:id])

		if @skill.update_attributes(params[:skill].permit(:skill_name, :skill_description))
			redirect_to action: 'show', id: @skill
		else
			render 'edit'
		end
	end

	def destroy
		Skill.find(params[:id]).destroy
		redirect_to :back
		# redirect_to skills_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    # i dont know if this works
    # @mentor = User.mentor.find_by(params[:user])
    # @learner = User.learner.find_by(params[:user])
  end

  def new
  	@user = User.new
  end

  def create
	@user = User.create(params[:user].permit(:name, :email, :password, :password_confirmation))
  @user.save

  user = User.find_by(email: params[:user][:email])
	 if user.authenticate(params[:user][:password])
        session[:user_id] = user.id
        redirect_to user
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user].permit(:user_name, :user_email, :user_password, :user_password_confirmation))
      redirect_to action: 'show', id: @user
    else
      render 'edit'
    end
  end
  


  
end

app/helpers/application_helper.rb
module ApplicationHelper
def full_title(page_title)
    base_title = "Wanderlust.co"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentications/_form.html.erb
<%= form_for User.new, {url:"/authentications", method:"post"} do |f| %>

	<%# f.label :email, "Email" %>
	<%= f.text_field :email, placeholder: "Email" %>

	<%# f.label :password, "Password" %>
	<%= f.password_field :password, placeholder: "Password"%>

	<%= f.submit "Sign in" %>

	<% end %>



<!-- <form class="form-inline" role="form"> -->
<%# form_for User.new, {url:"/authentications", method:"post"} do |f| %>

	<!-- <div class="form-group"> -->
	<%# f.label :email, "Email", class: "sr-only" %>
	<%# f.text_field :email, placeholder: "Email", class: "form-control" %>
	<!-- </div> -->

	<!-- <div class="form-group"> -->
	<%# f.label :password, "Password", class: "sr-only" %>
	<%# f.text_field :password, placeholder: "Password", class: "form-control" %>
	<!-- </div> -->

	<%# f.submit "Sign in", class: "btn btn-default myBtn" %>

	<%#end %>

<!-- </form> -->

app/views/authentications/destroy.html.erb
<%= session[:user_id] %>

app/views/authentications/new.html.erb
<% provide(:title, 'Sign In') %>

<h1>Sign In</h1>
  
    <%= form_for(@user) do |f| %>
   
      	<%= f.label :email %>
	    <%= f.text_field :email %>
      
	    <%= f.label :password %>
	    <%= f.password_field :password %>

	   <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
     <% end %>
  


<%# form_for @user, {url:"/authentications", method:"post"} do |u| %>
<!-- <br />
<br />
<br />


<%# u.label :email, "Email" %>
<%# u.text_field :email %>

<%# u.label :password, "Password" %>
<%# u.text_field :password %>

<%# u.submit "Sign in" %>

<br />
<br />
<br />


<%#end %>

</div> -->

app/views/categories/_checkboxes.html.erb
<!-- use this one -->

<%= form_tag :action => "update" do %>
<table class="table table-hover">
	<tr>
		<th>Mentors</th>
		<th>Learners</th>
		<th>Skills</th>
	</tr>

	<% @category.skills.each do |s| %>
		<tr>
			<td><%= check_box_tag "m" + s.id, "Y" %></td>
			<td><%= check_box_tag "l" + s.id, "Y" %></td>
			<td><%= s.skill_name %></td>
		</tr>
	<% end %>
</table>
	<p>
		<%= button_to "Submit", categories_url + "/_", method: :put %>	
	</p>


<% end %>

</div>

app/views/categories/index.html.erb
 <% provide(:title, 'All Categories') %>

<div class="form_container">

	<h1>Categories and Skills</h1>

	<table class="table table-hover">
		<tr>
			<th colspan="2">Category</th>
			<th>Skills</th>
			<!-- <th>Show</th>
			<th>Edit</th>
			<th>Remove</th> -->
		</tr>

		<% @categories.each do |c| %>
		<tr>
			<td colspan="2">
			<%= link_to c.category_name, category_path(c.id) %>
			</td><br />

			<td></td><td></td><td></td><td></td></tr>
			<% c.skills.each do |s|%>
		<tr>
			<td></td><td></td>	
			<td><%=s.skill_name %></td>
			<!-- <td><%# link_to 'Show', s %></td>
	        <td><%# link_to 'Edit', {controller: "skills", action:"edit", id:s.id}, {method: :get} %></td>
	        <td><%# link_to 'Delete', {controller: "skills", action:"destroy", id:s.id}, 
	        {method: :delete} %></td> -->
		</tr>
			<% end %>
		<% end %>
	</table>
</div>

app/views/categories/show.html.erb
<% provide(:title, 'All skills') %>

<div class="form_container">

<h1><%=@category.category_name %></h1>

<!-- i want to list the skills based on category -->
<!-- how to link the category id with skill id -->
<!-- do i need to put it in a partial? -->

	<!-- <div>
		<%#collection_select(:skill, :category_id, Category.all, :id, :category_name, prompt: 'Please select a category') %>
	</div> -->


<!-- <table class="table table-hover">
	<tr>
		<th></th>
		<th>Skills</th>
		<th>Show</th>
		<th>Edit</th>
		<th>Remove</th>
	</tr> -->

	
	<%= render 'categories/checkboxes.html.erb' %>
<%# form_for @skill, {url: '/skills', method: 'post'} do |f| %>

	<!-- <p> -->
		<%# collection_select(:skill, :category_id, Category.all, :id, :category_name, prompt: 'Please select a category') %>
	<!-- </p> -->



<%#@category.skills.each do |s| %>
	<!-- <tr> -->
		<!-- <td><%# check_box_tag "skill[category_ids][]", s.id %></td> -->
		<!-- <td><%# s.skill_name %></td> -->

		<!-- i still need to link edit btn with edit html -->
		<td><%# link_to 'Show', s %></td>
		<td><%# link_to "Edit", { controller: "skills", action: "edit", id: s.id}, {method: :edit} %></td>
		<td><%# link_to "delete", { controller: "skills", action: "destroy", id: s.id}, 
			{method: :delete, data:{confirm: "Are you sure?"}} %></td>
		<!-- <td><%# link_to 'Edit', edit_skill_path %></td> -->
	</tr>
	<p>
		<!-- this needs to update the skill -->
		<%# s.submit "Update" %>	
	</p>

	<%#end %>

	</tbody>
</table>

</div>


<div class="form_container">

	<h1>New Skill Form</h1>

	<%= render 'categories/form_new_skill' %> 

	<%# form_for @skill, {url: '/skills', method: 'post'} do |f| %>


	<!-- <p>
		<%#collection_select(:skill, :category_id, Category.all, :id, :category_name, prompt: 'Please select a category') %>
	</p>

	<p>
		<%# f.label :skill_name, "Skill" %><br />
		<%# f.text_field :skill_name %>
	</p>

	<p>
		<%# f.label :skill_description, "Skill Description" %><br />
		<%# f.text_area :skill_description %>
	</p>-->

	<!-- <p>
		<%# f.label :mentors, "I want to be a mentor"%>
		<%# f.radio_button :m_or_l, "mentor" %>
	</p> 

	<p>
		<%# f.label :learners, "I want to be a learner"%>
		<%# f.radio_button :m_or_l, "learner" %>
	</p> 

	<p>
		<%# f.submit %>	
	</p>

	<%#end %> -->

	<p><%= link_to 'back', categories_path %></p>


</div>












<%#provide(:title, @category.category_name) %>

<!-- <div class="form_container"> -->

	<!-- <h1><%# @category.category_name %></h1> -->


	
	<%#@category.skills.each do |s| %>
		<!-- <div><%# s.skill_name %></div> -->
	

	<%#end %>

<!-- </div> -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Wanderlust.co</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header ">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Wanderlust.co</a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Categories", categories_path %></li>
      <li><%= link_to "Skills", skills_path %></li>

    <div class = "rightside">
      <ul class="nav navbar-nav navbar-right">

      <% if current_user %>  
        <li><%= current_user.email %></li>
        <li><%= button_to "logout", "/authentications/_", method: "delete" %></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"><b class="caret"></b></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Mentors", mentors_path %></li>
          <li><%= link_to "Learners", learners_path %></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
        <!-- <li><%# link_to "Profile", current_user %></li>
        <li><%# link_to "Mentors", mentors_path %></li>
        <li><%# link_to "Learners", learners_path %></li> -->
    </div>                 
      <% else %>
        <%= render "authentications/form" %>
      <% end %>
  </nav> 

	




	

app/views/layouts/_header_old.html.erb
<header class="navbar navbar-default navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <%#if signed_in? %>
            <!-- <li><%# link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%# link_to "Profile", current_user %></li>
                <li><%# link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%# link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <%#else %> -->
            <li><%= link_to "Sign in", signin_path %></li>
          <%#end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

<% if current_user %>  
      <%= current_user.email %>
      <%= button_to "logout", "/authentications/_", method: "delete" %>
    <% else %>
      <%= render "authentications/form" %>
    <% end %>

app/views/learners/index.html.erb
<% provide(:title, 'All Learners') %>

<div class="form_container">

<h1>Learners and Skills</h1>

	
<table class="table table-hover">

<tr>
	<th colspan="2">LEARNERS</th>
	<th>SKILL NAME</th>
	<th>SKILL DESCRIPTION</th>
	<!-- <th>Show</th>
	<th>Edit</th>
	<th>Remove</th> -->
</tr>


<% @learners.each do |l| %>
<tr>
	<td colspan="2"><%= link_to l.user.email, l %></td><br />

	<% l.skills.each do |s| %>

		<td><%= s.skill_name %></td>
		<td><%= s.skill_description %></td>
		<td><%# link_to 'Show', s %></td>
        <td><%# link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%# link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
<% end %>

</table>
</div>

app/views/learners/show.html.erb
<% provide(:title, "Learner Info") %>

<div class= "form_container">

<table class="table table-hover">
	
	<tr>
		<th>Skill Name</th>
		<th>Skill Description</th>
		<th>Learner Name</th>
		<th>Notes</th>
	</tr>

	<tr>
		<% @learner.skills.each do |ls| %>
		<td><%= ls.skill_name %></td>
		<td><%= ls.skill_description %></td>
		<% end %>

		<td><%= @learner.user.email %></td>
		<td><%= @learner.notes %></td>
	</tr>
</table>

<br />
<br />
<br />
<p><%= link_to 'Back', learners_path %></p>

</div>

app/views/mentors/index.html.erb
<% provide(:title, 'All Mentors') %>

<div class="form_container">

<h1>Mentors and Skills</h1>

	
<table class="table table-hover">

<tr>
	<th colspan="2">MENTORS</th>
	<th>SKILL NAME</th>
	<th>SKILL DESCRIPTION</th>
	<!-- <th>Show</th>
	<th>Edit</th>
	<th>Remove</th> -->
</tr>

<% @mentors.each do |m| %>
	
<tr>
	<td colspan="2"><%= link_to m.user.email, m %></td><br />
	<% m.skills.each do |s| %>
		<td><%= s.skill_name %><%#end %></td>
		<td><%= s.skill_description %><% end %></td>
		<td><%# link_to 'Show', s %></td>
        <td><%# link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%# link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

<% end %>

</table>
</div>

app/views/mentors/show.html.erb
<% provide(:title, 'Mentor Info') %>

<div class= "form_container">

<table class="table table-hover">

	<tr>
		<th>Skill Name</th>
		<th>Skill Description</th>
		<th>Mentor Name</th>
		<th>Notes</th>
	</tr>

	<tr>

	<% @mentor.skills.each do |ms| %>
		<td><%= ms.skill_name %></td>
		<td><%= ms.skill_description %></td>
		<% end %>

		<td><%= @mentor.user.email %></td>
		<td><%= @mentor.notes %></td>
	</tr>
</table>

<br />
<br />
<br />
<p><%= link_to 'Back', mentors_path %></p>

</div>

app/views/skills/_default_view.html.erb
<% provide(:title, @skill.skill_name) %>

<div class = "form_container">

<table class="table table-hover">

	<tr>
		<th>Skill Name</th>
		<th>Skill Description</th>
		<th>Mentors Name</th>
		<th>Learners Name</th>
	</tr>
	<tr>
		<td><%= @skill.skill_name %></td>
		<td><%= @skill.skill_description %></td>

	<% @skill.mentors.each do |sm| %>
		<td><%= sm.user.email %>
		<% end %></td>
		<!-- try to put an if statement so if no mentors to leave blank -->

	<% @skill.learners.each do |lm| %>
		<td><%= lm.user.email %><% end %></td>
		
	</tr>


</table>	



<br />
<br />
<br />

<p><%= link_to 'Back', skills_path %></p>

</div>

app/views/skills/_skill_learners_view.html.erb
<% provide(:title, @skill.skill_name) %>

<div class = "form_container">

<h1>skill learners view</h1>

<table class="table table-hover">

	<tr>
		<th>Skill Name</th>
		<th>Skill Description</th>
		<th>Learners Name</th>
		<th>Learners Notes</th>
	</tr>
	<tr>
		<td><%= @skill.skill_name %></td>
		<td><%= @skill.skill_description %></td>
	</tr>

		<% @skill.learners.each do |lm| %>
	<tr>
	<td></td><td></td>
			<td><%= lm.user.email %>
			</td>

			<td><%= lm.notes %>
			</td>
	</tr>
		<% end %>
	
</table>	



<br />
<br />
<br />
<p><%= link_to 'Back', skills_path %></p>
</div>

app/views/skills/_skill_mentors_view.html.erb
<% provide(:title, @skill.skill_name) %>

<div class = "form_container">

<h1>skill mentors view</h1>

<table class="table table-hover">

	<tr>
		<th>Skill Name</th>
		<th>Skill Description</th>
		<th>Mentors Name</th>
		<th>Mentors Notes</th>
	</tr>
	<tr>
		<td><%= @skill.skill_name %></td>
		<td><%= @skill.skill_description %></td>

		<% @skill.mentors.each do |sm| %>
			<td><%= sm.user.email %>
			</td>

			<td><%= sm.notes %>
			</td>

		<% end %>
	</tr>
</table>	



<br />
<br />
<br />
<p><%= link_to 'Back', skills_path %></p>
</div>

app/views/skills/index.html.erb
<% provide(:title, 'All skills') %>

<div class="form_container">
	<h1>i got skills!</h1>
	<table class="table table-hover">
		<tr>
			<th>SKILLS</th>
			<th>MENTORS</th>
			<th>LEARNERS</th>
			<!-- <th>Show</th>
			<th>Edit</th>
			<th>Remove</th> -->
		</tr>

	<% @skills.each do |s| %>
		<tr>
			<td><%= link_to s.skill_name, skill_path(s.id) %></td>
			<td><div class="form_circle m_circle"><%= link_to s.mentors.count, skill_path(s, view: "mentors") %></div></td>
			<td><div class="form_circle l_circle"><%= link_to s.learners.count, skill_path(s, view: "learners") %></div></td>

		<td><%#s.mentors.each do |m| %>
			<%# link_to m.user.email, mentors_path(id: m.id) %>
		<%#end %></td>
			
		<td><%#s.learners.each do |l| %>
			<%# link_to l.user.email, learners_path(id: l.id) %>
			<!-- <td><%# link_to "Show", s %></td>
			<td><%# link_to "Edit", { action: "edit", id: s.id},
			{method: :get} %></td>
			<td><%# link_to "Delete", { action: "destroy", id: s.id}, 
			{method: :delete, data:{confirm: "Are you sure?"}} %></td> -->
			<!-- Not sure why the edit path below doesnt work -->
			<!-- <td><%# link_to 'Edit', edit_skills_path(s) %></td> -->
		
		
	<%#end %></td>
	</tr>
	<% end %>
	</table>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="form_container row">

	<% if current_user %>
	<h1> Welcome <%= @user.email %></h1>
	<%= link_to 'edit profile', edit_user_path %>

	<div class="profile_container right">
	<table class="table table-hover">
		<tr>
			<th>Skills</th>
			<!-- <th>Show</th> -->
			<th>Edit</th>
			<th>Remove</th>
		</tr>

		<h3>Skills I'm Teaching</h3>
		<tbody>
		<% @user.mentors.each do |m| %>
			<% m.skills.each do |s| %>
		<tr>
			<td><%= link_to s.skill_name, m %> </td>
			<!-- <td><%# link_to 'Show', m %></td> -->
			<td><%= link_to "Edit", { controller: "skills", action: "edit", id: s.id}, {method: :get} %></td>
			<td><%= link_to "delete", { controller: "skills", action: "destroy", id: s.id}, 
			{method: :delete, data:{confirm: "Are you sure?"}} %></td>
		</tr>
		<% end %>
		<% end %>
		</tbody>
	</table>
	</div>


	<div class="profile_container left">
	<table class="table table-hover">
		<tr>
			<th>Skills</th>
			<!-- <th>Show</th> -->
			<th>Edit</th>
			<th>Remove</th>
		</tr>
		<h3>Skills I'm Learning</h3>
		<tbody>
		<% @user.learners.each do |l| %>
			<% l.skills.each do |s| %>
		<tr>
			<td><%= link_to s.skill_name, l %> </td>
			<!-- <td><%# link_to 'Show', l %></td> -->
			<td><%= link_to "Edit", { controller: "skills", action: "edit", id: s.id}, {method: :get} %></td>
			<td><%= link_to "delete", { controller: "skills", action: "destroy", id: s.id}, 
			{method: :delete, data:{confirm: "Are you sure?"}} %></td>
		</tr>
		<% end %>
		<% end %>
		</tbody>
	</table>
	</div>

	<% end %>
</div>